### ISSUE TITLE
bold highlighting of keyword in thumbnail video viewer sometimes highlights wrong word.

### ISSUE THREAD

**Issue by magrawala** [jhong93/esper-tv-widget#5]
bold highlighting of caption.text word doesn't work correctly. Sometimes the word before the keyword is highlighted.

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20onscreen.face%3D%5C%22Donald%20Trump%5C%22%20AND%20caption.text%3D%5C%22presidential%5C%22%22%7D%5D%7D

**Comment by kayvonf** [comment]
The player is highlighting the transcript word that corresponds to the video's current video time. (essentially it's a cursor for where we are in the video.  If you press play you'll see the highlighted term change.) This is confusing behavior.

This bold text is not a visualization of the search term.  This issue is a request to highlight the caption search term in the playback widget *in addition to* the cursor highlight.

**Comment by jhong93** [comment]
Added this.
