### ISSUE TITLE
screen time of men and women is trending up... even after normalizing

### ISSUE THREAD

**Issue by kayvonf** [jhong93/esper-tv-widget#9]
This is an interesting example of where normalization by screen time yields a result that's a little different than I expected.  This is a plot of male vs. female screen time, but it is normalized to total video time.  

Notice that it goes up over time, it is not flat.  This suggests that the number of faces in the dataset is increasing over time.  If query was a COUNT FACE TIME query, normalized by total face time, it would be the flat graph that we typically show.

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20onscreen.face%3Dmen%20NORMALIZE%20all%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22%20WHERE%20onscreen.face%3Dwomen%20NORMALIZE%20all%22%7D%5D%7D

**Comment by kayvonf** [comment]
This is what I was expecting to get when I originally wrote the query.

http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22facetime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22men%20WHERE%20NORMALIZE%20all%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22women%20WHERE%20NORMALIZE%20all%22%7D%5D%7D

**Comment by jhong93** [comment]
This is expected behavior; the average number of faces on screen has been trending up over the 10 years.

This plot is closer to your second plot. It normalizes by the amount of time there is any face on screen.
http://esper-tv.stanford.edu/?data=%7B%22options%22%3A%7B%22start_date%22%3A%222010-01-01%22%2C%22end_date%22%3A%222018-04-01%22%2C%22count%22%3A%22videotime%22%2C%22aggregate%22%3A%22month%22%7D%2C%22queries%22%3A%5B%7B%22color%22%3A%22%234E79A7%22%2C%22text%22%3A%22%20WHERE%20onscreen.face%3Dmen%20NORMALIZE%20onscreen.face%3Dall%22%7D%2C%7B%22color%22%3A%22%23F28E2B%22%2C%22text%22%3A%22%20WHERE%20onscreen.face%3Dwomen%20NORMALIZE%20onscreen.face%3Dall%22%7D%5D%7D
